# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

trigger:
- main

variables:
  azureSubscription: 'MCAPS-Support-REQ-79228-2024-v-dnjoku'
  functionAppName: 'azurefunctionajet'
  pythonVersion: '3.9'
  artifactName: 'functionapp.zip'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Set up Python $(pythonVersion)'

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifactName)'
      displayName: 'Archive files'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(artifactName)'
        artifact: 'functionapp'
      displayName: 'Publish Artifact'

- stage: Deploy
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'current'
        artifactName: 'functionapp'
        path: '$(Pipeline.Workspace)'
      displayName: 'Download Artifact'

    - task: AzureFunctionApp@2
      inputs:
        azureSubscription: $(azureSubscription)
        appType: functionAppLinux
        appName: $(functionAppName)
        package: '$(Pipeline.Workspace)/functionapp.zip'
        runtimeStack: 'PYTHON|$(pythonVersion)'
      displayName: 'Deploy to Azure Function App'
